const fs = require('fs');

const fullCatchplayList = [
  "Spider-Man: No Way Home (Extended Version)",
  "Demon Slayer: Kimetsu no Yaiba Infinity Castle I",
  "Operation Fortune: Ruse de guerre",
  "The Pirates",
  "Sound of Freedom",
  "The King's Warden",
  "Greenland 2: Migration",
  "Michael",
  "The Unrighteous",
  "The Bone Collector",
  "The Amazing Spider-Man",
  "Hellboy: The Crooked Man",
  "Memories of the Sword",
  "My Sole Desire",
  "Silent Zone",
  "Dracula: A Love Tale",
  "Pitfall",
  "The Housemaid",
  "Hi-Five",
  "Wrath of Man",
  "The Amazing Spider-Man 2",
  "The Beekeeper",
  "The Old Woman with the Knife",
  "Aquaman and the Lost Kingdom",
  "Supergirl (Premier Perdana)",
  "Spider-Man: No Way Home",
  "Spider-Man 3",
  "Eun-gyo",
  "Special Ops: Lioness",
  "Concrete Market",
  "The Wolf of Wall Street",
  "Shelter",
  "Evil Dead",
  "Lee Cronin's The Mummy",
  "The Damned",
  "The Treacherous",
  "Mortal Kombat II",
  "Spider-Man: Homecoming",
  "Once We Were Us",
  "The Super Mario Galaxy Movie",
  "Spider-Man: Far from Home",
  "Seven Snipers",
  "Salmokji: Whispering Water",
  "Hokum",
  "Harry Potter and the Sorcerer's Stone",
  "Spider-Man",
  "I Was a Stranger",
  "Passenger",
  "Interstellar",
  "Basic Instinct",
  "Insidious: Chapter 2",
  "Heretic",
  "Cleaner",
  "All the Way",
  "Spider-Man 2",
  "The Divine Fury",
  "Bloody Smart",
  "Chloe",
  "The Conjuring",
  "Lost",
  "Shame",
  "The Conjuring 2",
  "The Departed",
  "Spider-Man: Into the Spider-Verse",
  "In the Lost Lands",
  "John Wick: Chapter 4",
  "Second Sister",
  "Keeper",
  "Brave Citizen",
  "Love in the Big City",
  "Children...",
  "Utusan Iblis: Dia Yang Berada di Antara Kita",
  "Subservience",
  "Apocalypto",
  "The Nun",
  "The Reader",
  "Dark Spell",
  "Love, Lies",
  "The Ritual",
  "The Neighbors",
  "The Miniature Wife",
  "Canary Black",
  "The Superdeep",
  "M.I.A.",
  "Hidden Strike",
  "Holy Night: Demon Hunters",
  "Rebirth Island",
  "Absolution",
  "Last Summer",
  "Hope",
  "Yadang: The Snitch",
  "Arwah",
  "Pee Nak 5",
  "Harry Potter and the Deathly Hallows: Part 1",
  "Annabelle Comes Home",
  "The Conjuring: Last Rites",
  "Innocent Thing",
  "Inglourious Basterds",
  "The Agency: Central Intelligence",
  "Insidious: Chapter 3",
  "Omniscient Reader: The Prophecy",
  "Legends of the Condor Heroes: The Gallants",
  "Tarot",
  "Insidious: The Last Key",
  "Misbehavior",
  "Islanders",
  "Along with the Gods: The Two Worlds",
  "Evil Dead Rise",
  "The Closet",
  "Harry Potter and the Half-Blood Prince",
  "Harry Potter and the Chamber of Secrets",
  "Mission: Impossible - The Final Reckoning",
  "Final Destination: Bloodlines",
  "Oppenheimer",
  "Harry Potter and the Prisoner of Azkaban",
  "Harry Potter and the Deathly Hallows: Part 2",
  "Inception",
  "We Bury the Dead",
  "Tenet",
  "Harry Potter and the Goblet of Fire",
  "The Hobbit: An Unexpected Journey (Extended Edition)",
  "We Live in Time",
  "Harry Potter and the Order of the Phoenix",
  "Shaolin Soccer",
  "The Hobbit: The Desolation of Smaug (Extended Edition)",
  "Weapons",
  "Zack Snyder's Justice League",
  "Spider-Man: Across the Spider-Verse",
  "Superman",
  "Den of Thieves: Pantera",
  "Crazy Rich Asians",
  "The Dark Knight Rises",
  "The Dark Knight",
  "Dune",
  "They Will Kill You",
  "Relay",
  "Whistle",
  "The Lord of the Rings: The Fellowship of the Ring (Extended Edition)",
  "The Nun II",
  "Dune: Part Two",
  "Batman Begins",
  "Wuthering Heights",
  "The Hobbit: The Battle of the Five Armies (Extended Edition)",
  "Warfare",
  "Sonic the Hedgehog 3",
  "Scream 7",
  "Murder Report",
  "The Long Walk",
  "Meg 2: The Trench",
  "The Lord of the Rings: The Return of the King (Extended Edition)",
  "Justice League",
  "A Minecraft Movie",
  "The Conjuring: The Devil Made Me Do It",
  "Afterburn",
  "The Strangers: Chapter 2",
  "It Ends With Us",
  "Wildcat",
  "Me Before You",
  "The Angry Birds Movie",
  "Black Phone 2",
  "A Man Called Otto",
  "The Lord of the Rings: The Two Towers (Extended Edition)",
  "Top Gun: Maverick",
  "28 Years Later",
  "Karate Kid: Legends",
  "That Time I Got Reincarnated as a Slime the Movie: Scarlet Bond",
  "The Exorcist: The Version You've Never Seen",
  "Fantastic Beasts and Where to Find Them",
  "Fantastic Beasts: The Secrets of Dumbledore",
  "Transformers One",
  "The Batman",
  "Transformers: Rise of the Beasts",
  "Dunkirk",
  "One Battle After Another",
  "Joker",
  "Sniper: No Nation",
  "Primate",
  "Gladiator II",
  "Sisu",
  "Anyone But You",
  "Sonic the Hedgehog 2",
  "mother!",
  "Transformers: Dark Of The Moon",
  "It: Chapter Two",
  "The Super Mario Bros. Movie",
  "Insidious: The Red Door",
  "PAW Patrol: The Mighty Movie",
  "The SpongeBob Movie: Search for SquarePants",
  "Rings",
  "Novocaine",
  "Captain Phillips",
  "Concubine",
  "Borders of Love",
  "Love at the End of the World",
  "Girls to Buy",
  "In the Room",
  "Moebius",
  "Come Undone",
  "My Sex Doll Bodyguard",
  "Nineteen: Shh! No Imagining!"
];

let pageCode = fs.readFileSync('app/page.tsx', 'utf8');
const pageArrayStr = JSON.stringify(fullCatchplayList, null, 6).replace(/\]/g, '    ]');
pageCode = pageCode.replace(/movies:\s*\[[\s\S]*?\],\s*updatedAt:\s*1771706900000/, (match) => {
    if (match.includes("Spider-Man: No Way Home")) {
        return 'movies: ' + pageArrayStr + ',\n    updatedAt: 1771706900000';
    }
    return match;
});
fs.writeFileSync('app/page.tsx', pageCode);

let scrapeCode = fs.readFileSync('scripts/scrape.js', 'utf8');
const scrapeArrayStr = JSON.stringify(fullCatchplayList, null, 4).replace(/\]/g, '  ]');
scrapeCode = scrapeCode.replace(/const idFallback = \[[^;]+\];/m, 'const idFallback = ' + scrapeArrayStr + ';');
fs.writeFileSync('scripts/scrape.js', scrapeCode);

console.log("Updated both app/page.tsx and scripts/scrape.js with the full 200 items list.");
